## Model Testing

In [1]:
import joblib
import pandas as pd
import numpy as np
import os

In [2]:
example_df=pd.read_csv('C:/Users/Admin/Desktop/sample.csv',na_values=[""],keep_default_na=False)

In [3]:
example_df.head(9)

,Food Product,Main Ingredient,Sweetener,Fat/Oil,Seasoning,Allergens,Price ($),Customer rating (Out of 5)
0,Blueberry Protein Bar,Blueberries,Honey,Almond oil,Vanilla extract,Tree nuts,2.99,4.2
1,Mango Chia Pudding,Mango,Coconut sugar,Coconut milk,Cardamom,Coconut,4.49,4.5
2,Beetroot Chips,Beetroot,None,Olive oil,Sea salt,None,3.25,3.8
3,Pumpkin Spice Muffin,Pumpkin,Maple syrup,Butter,"Cinnamon, Nutmeg","Wheat, Dairy",5.75,4.7
4,Lentil Soup,Lentils,None,Olive oil,Herbs de Provence,None,4.00,4.0
5,Quinoa Sushi Roll,Quinoa,None,Avocado oil,Soy sauce,Soy,6.50,4.6
6,Turmeric Latte,Turmeric,Date syrup,Coconut oil,"Ginger, Black pepper",None,3.75,4.3
7,Seaweed Snack,Seaweed,None,Sesame oil,Nori seasoning,None,2.50,3.9
8,Hazelnut Milkshake,Hazelnuts,Agave syrup,Hazelnut oil,Cocoa powder,Tree nuts,5.25,4.8

In [4]:
# Rename the columns
example_df.rename(columns={'Price ($)': 'Price', 'Customer rating (Out of 5)': 'Customer rating'}, inplace=True)

In [5]:
# Load the model and encoder from the file
encoder_path='C:/Users/Admin/Desktop/food_allergen_detection/Models/encoder.pkl'
model_path = 'C:/Users/Admin/Desktop/food_allergen_detection/Models/rf_model.pkl'

encoder=joblib.load(encoder_path)
rf_model = joblib.load(model_path)

In [6]:
categorical_columns = ['Food Product', 'Main Ingredient', 'Sweetener', 'Fat/Oil', 'Seasoning','Allergens']

example_df_encoded=encoder.transform(example_df[categorical_columns])

example_df=pd.concat([example_df.drop(categorical_columns,axis=1),example_df_encoded],axis=1)

In [7]:
example_df

,Price,Customer rating,Food Product,Main Ingredient,Sweetener,Fat/Oil,Seasoning,Allergens
0,2.99,4.2,12.397588,12.397588,13.235000,12.397588,12.246250,12.397588
1,4.49,4.5,12.397588,9.720000,12.397588,10.597778,12.397588,12.397588
2,3.25,3.8,12.397588,12.397588,12.397599,13.094000,12.397588,12.165608
3,5.75,4.7,12.397588,13.792500,12.397588,12.444471,12.397588,13.050563
4,4.00,4.0,11.245000,11.790000,12.397599,13.094000,12.397588,12.165608
5,6.50,4.6,12.397588,13.760000,12.397599,12.397588,13.071333,12.397588
6,3.75,4.3,12.397588,12.397588,12.397588,12.397588,12.397588,12.165608
7,2.50,3.9,12.397588,12.397588,12.397599,13.510000,12.397588,12.165608
8,5.25,4.8,12.397588,12.397588,12.397588,12.397588,16.560000,12.397588
9,6.00,4.1,12.397588,12.397588,12.397599,12.162586,12.397588,12.165608

In [8]:
# Make predictions using the loaded model
prediction = rf_model.predict(example_df)

print(prediction)

[0 0 1 0 1 0 1 1 0 1]